// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiyoqzayuifquinknjae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpeW9xemF5dWlmcXVpbmtuamFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIwODUsImV4cCI6MjA2NTQ4ODA4NX0.qgj_k6CXARi0wDzsqFFz6wx6enjSnYcELuHuXBH8MG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);